
spring:
    profiles: 
        active: DEV

---
spring:
    profiles: DEV
wishlist:
   profiles: development
application:
     name: customer-profile-job
datasource:
     driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
     url: "jdbc:sqlserver://VTP3102\\\\MSSQLSERVER2012:65239;DatabaseName=SFCC_Commerce;integratedSecurity=true;sendStringParametersAsUnicode=false;responseBuffering=adaptive"

hibernateproperties:
  showSql: true
  useSqlComments: true
  formatSql: true
  databasePlatform: org.hibernate.dialect.SQLServer2008Dialect
  hibernateDdlAuto: update
---
spring:
    profiles: QA
wishlist:
application:
     name: customer-profile-job
datasource:
     driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
     url: jdbc:sqlserver://tlbvm611.ecom.corp.talbots.com;DatabaseName=SFCC_Commerce;integratedSecurity=true;sendStringParametersAsUnicode=false;responseBuffering=adaptive

hibernateproperties:
  showSql: true
  useSqlComments: true
  formatSql: true
  databasePlatform: org.hibernate.dialect.SQLServer2008Dialect
  hibernateDdlAuto: update
---
spring:
    profiles: PROD
wishlist:
application:
     name: customer-profile-job
datasource:
     driverClassName: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
     url: jdbc:sqlserver://ecosql09.ecom.corp.talbots.com;DatabaseName=SFCC_Commerce_V1;integratedSecurity=true;sendStringParametersAsUnicode=false;responseBuffering=adaptive

hibernateproperties:
  showSql: true
  useSqlComments: true
  formatSql: true
  databasePlatform: org.hibernate.dialect.SQLServer2008Dialect
  hibernateDdlAuto: update