SELECT distinct u.id AS id, 
          u.login, 
		  sfu.password,   
		  u.first_name, 
		  u.last_name, 
		  u.email, 
		  u.gender,  
		  cc.billing_addr as addressId,
          c.first_name as "ad_first_name",  
		  c.last_name as "ad_last_name", 
		  c.address1, 
		  c.address2, 
		  c.address3, 
		  c.city, c.state, 
          c.postal_code, 
		  c.country, 
		  c.phone_number,
		  dbo.csys_contact_info.address4,
		  dbo.csys_contact_info.nickname, 
		  dbo.csys_contact_info.location, 
		  dbo.csys_contact_info.day_phone, 
          dbo.csys_contact_info.evening_phone,
		  dbo.tlb_user.birth_month,
          dbo.tlb_user.us_citizen_status, 
	      dbo.tlb_user.classic_awards_member,
		  dbo.tlb_user.classic_awards_member_number, 
          dbo.tlb_user.receieve_promo_updates
		  ,csu.promo_signup
		  
FROM     dbo.dps_user AS u LEFT OUTER JOIN
                      dbo.tlb_user ON u.id = dbo.tlb_user.id LEFT OUTER JOIN
                      dbo.csys_contact_info RIGHT OUTER JOIN
                      dbo.dps_usr_creditcard AS uc INNER JOIN
                      dbo.dps_credit_card AS cc ON uc.credit_card_id = cc.id INNER JOIN
                      dbo.dps_contact_info AS c ON cc.billing_addr = c.id ON dbo.csys_contact_info.id = c.id ON u.id = uc.user_id
					  left join sfcc_commerce.dbo.csys_user csu on u.id = csu.id
					  left join sfcc_commerce.dbo.sfcc_dps_user sfu on u.id = sfu.id				 
					 where processed=1
 and  login in (
 'AMYSMITH3908@YAHOO.COM',
'gallen@mail.nih.gov',
'CWIEWIOROWSKI@GMAIL.COM',
'JANSIMS@AUGUSTA.EDU',
'TMWILLIAMS1965@GMAIL.COM',
'EW6639@ATT.COM',
'FELLR@MSN.COM',
'GLENDAOCO@OPTONLINE.NET',
'STEPHFISHER94@GMAIL.COM',
'CHEBRON@VISITATIONACADEMY.ORG',
'DANIERRN@GMAIL.COM',
'LISA.COALSON@GMAIL.COM',
'MARCIA.NORDGREN@NORDGRENLAW.COM',
'GAIL.EDWARDS6@AOL.COM',
'LTIPNAP@ATT.NET',
'bpdoylestown@gmail.com',
'RCBOWERS@CAROLINA.RR.COM',
'EVIECOOPER@ATT.NET',
'VCGROOMWILSON@GMAIL.COM',
'FSANOV@AOL.COM',
'harp7803@bellsouth.net',
'BCRAW74@GMAIL.COM',
'djc0729@gmail.com',
'helen@avisionofyourown.com',
'SUSAN_JONES@CONTRASTCOMMUNICATIONS.COM',
'am1356@att.net',
'HAYES.MEDIA@ME.COM',
'DLWR06@GMAIL.COM',
'mewalters101@gmail.com',
'EVERESTJ@AOL.COM',
'KARENLATE@HOTMAIL.COM',
'higgs631@msn.com',
'WORKINGCATTLEDOGS@GMAIL.COM',
'VCNATION@COMCAST.NET',
'fsgomez@att.net',
'KARENRARICK228@GMAIL.COM',
'NANCY-DOUGHTY@ATT.NET',
'erussellhorton@gmail.com',
'JAMESGANG@SBCGLOBAL.NET',
'MSBRICH@GMAIL.COM',
'BABIRD777@ICLOUD.COM',
'JLLOYDMK@GMAIL.COM',
'sniggih44@gmail.com',
'GALEMAYO1@GMAIL.COM',
'GATMEDINC@AOL.COM',
'esmcclay@gmail.com',
'RICEDORIS8@GMAIL.COM',
'TDOBRZYK@IUSB.EDU',
'SJADUR8@YAHOO.COM',
'CLASINIA@GMAIL.COM',
'JEANSTAMPS@VERIZON.NET',
'HARRISKC1@YAHOO.COM',
'gary_ang@msn.com',
'helainemacphail@hotmail.com',
'MRSMACK@MAC.COM',
'KSPARRIGO@GMAIL.COM',
'JBARAUSKY@VERIZON.NET',
'STEVENSON3944@WI.RR.COM',
'LOPEZFAMILY909@MSN.COM',
'GAYLEANDDAVID@MSN.COM',
'RANIASTOGO@GMAIL.COM',
'JUDITH.SCHWAGER@OUTLOOK.COM',
'MICANDSUESTARR@GMAIL.COM',
'rdix0531@gmail.com',
'fjlavrakas@gmail.com',
'OASHLEY58@GMAIL.COM',
'WELJAX21@YAHOO.COM',
'RFURROW05@GMAIL.COM',
'FROSTINE.BURKE@GMAIL.COM',
'fiona2go@gmail.com',
'JOHNSTON_PG@MERCER.EDU',
'EFAVERS@GMAIL.COM',
'VOSSM57@GMAIL.COM',
'MARIANNEMOTLEY@GMAIL.COM',
'KIMRAY215@GMAIL.COM',
'HURRYDENISE@GMAIL.COM',
'gftheart42@hotmail.com',
'MSANSBURY95@GMAIL.COM',
'CHARLOTTEPURKIS@VERIZON.NET',
'ERINKATE25@AOL.COM',
'yatesdeborah3@gmail.com',
'gig213@aol.com',
'DPOSTON1@GMAIL.COM',
'freeman.sherrys@gmail.com',
'STITCHWHIZ623@YAHOO.COM',
'haub.lit@live.com',
'LLW7@COMCAST.NET',
'KHIGGINS@4STARREPS.COM',
'escrouch@gmail.com',
'HEATHERMURPHY34@GMAIL.COM',
'teresaandgary85@gmail.com',
'GBFERGUS@BELLSOUTH.NET',
'ELLEN.FIGURA@GMAIL.COM',
'FOODIE1940@GMAIL.COM',
'REBECCA@ARRENBEE.COM',
'JOHANNESYLVIE@MSN.COM',
'JANCHARVAT1@GMAIL.COM',
'TJH23@ATT.NET',
'CAROLPCAIN@GMAIL.COM',
'ELAINEHAMILTON@ICLOUD.COM',
'Irene.connolly@talbots.com',
'Kayleneob@gmail.com'
)
order by u.id