FROM dockerfile/java:oracle-java8

VOLUME /tmp
ADD et-organization-service.jar /opt/et-organization-service/
EXPOSE 8080
WORKDIR /opt/et-organization-service/
CMD ["java", "-Djava.security.egd=file:/dev/./urandom", "-Xms512m", "-Xmx1g", "-jar", "et-organization-service.jar"]
