//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.25 at 03:51:38 PM EST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.demandware.com/xml/impex/customer/2006-10-31", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.talbots.xsd.model;
